services:
  cache:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '41773:1972'
      - '42773:57772'
    volumes:
      - ./:/opt/cacheapp

      - ../:/external
